---
  - name: Configure App
    hosts: app
    become: true

    vars:
     db_host: 10.166.15.207

    roles:
    - app
    
    handlers:
    - name: reload puma
      systemd: name=puma state=restarted
