---
  - name: Configure hosts & deploy application 
    hosts: all 
    vars:
      mongo_bind_ip: 0.0.0.0
      db_host: 10.166.15.199
    tasks: 
    - name: change mongo config file
      become: true 
      template:
        src: templates/mongod.conf.j2 
        dest: /etc/mongod.conf 
        mode: 0644
      tags: db-tag
    handlers:
    - name: restart mongod
      become: true
      service: name=mongod state=restarted
    - name: reload puma
      become: true
      systemd: name=puma state=restarted

  - name: Add unit file for Puma
    become: true
    copy:
      src: files/puma.service
      dsdt: /etc/systemd/system/puma.service
    tags: app-tag
    notify: reload puma

  - name: Add config for DB connection
    template:
      src: templates/db_config.j2
      dest: /home/appuser/db_config
    tags: app-tag
  
  
  - name: enable Puma
    become: true
    systemd: name=puma enabled=yes
    tags: app-tag


